### ISSUE TITLE
报错 “name 'objstudent' is not defined ”  

### ISSUE THREAD

**Issue by Kingofolk** [LutingWang/HEAD#1]
您好！
感谢您开源了您的ECCV的优秀论文HEAD的相关代码。您的工作对我很有启发，然而我在试图复现时遇到了一些问题。希望能得到您的帮助。
我执行了以下命令
python tools/train.py configs/HEAD/head_retina_faster_r18_mstrain_1x_coco.py --work-dir repoduce --gpus 1
代码报错name 'objstudent' is not defined。
请问该如何解决呢？或者您是否能够提供一份代码复现的指引呢。
敬祝夏安

**Comment by LutingWang** [comment]
同学你好～可以贴一下完整的traceback信息嘛？

**Comment by LutingWang** [comment]
同学你好，可以贴一下完整的traceback信息嘛？目前代码还在整理过程中，预计今明两天会有更详细的文档。感谢关注～～

**Comment by Kingofolk** [comment]
![IMG_20220731_171049](https://user-images.githubusercontent.com/37804732/182019367-70f9db8a-122d-472c-bf58-897ade56156d.jpg)
完整报错信息如上。麻烦您啦。

**Comment by Kingofolk** [comment]
完整报错信息如下，麻烦您啦！

Traceback (most recent call last):
  File "/usr/local/miniconda3/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/todd/distillers/base.py", line 185, in __call__
    obj._distiller = cls(obj, **distiller)
  File "/data1/resources/code/HEAD-refactor/HEAD-refactor/head/detectors.py", line 135, in __init__
    teacher_model = todd.utils.ModelLoader.load_mmlab_models(DETECTORS, **teacher)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/todd/distillers/teacher.py", line 97, in __init__
    super().__init__(student, **kwargs)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/todd/distillers/teacher.py", line 52, in __init__
    super().__init__(
  File "/usr/local/miniconda3/lib/python3.8/site-packages/todd/distillers/base.py", line 74, in __init__
    ModelLoader.load_state_dicts(self, weight_transfer)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/todd/utils/models.py", line 40, in load_state_dicts
    target_module = getattr_recur(models, target)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/todd/base/_extensions/builtins.py", line 21, in patch_func
    return f(obj, attr, *args, **kwargs)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/todd/base/_extensions/builtins.py", line 31, in getattr_recur
    return eval('obj' + attr)
  File "<string>", line 1, in <module>
NameError: name 'objstudent' is not defined

**Comment by Kingofolk** [comment]
完整报错信息如下，麻烦您啦！

Traceback (most recent call last):
  File "/usr/local/miniconda3/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/todd/distillers/base.py", line 185, in __call__
    obj._distiller = cls(obj, **distiller)
  File "/data1/resources/code/HEAD-refactor/HEAD-refactor/head/detectors.py", line 135, in __init__
    teacher_model = todd.utils.ModelLoader.load_mmlab_models(DETECTORS, **teacher)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/todd/distillers/teacher.py", line 97, in __init__
    super().__init__(student, **kwargs)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/todd/distillers/teacher.py", line 52, in __init__
    super().__init__(
  File "/usr/local/miniconda3/lib/python3.8/site-packages/todd/distillers/base.py", line 74, in __init__
    ModelLoader.load_state_dicts(self, weight_transfer)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/todd/utils/models.py", line 40, in load_state_dicts
    target_module = getattr_recur(models, target)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/todd/base/_extensions/builtins.py", line 21, in patch_func
    return f(obj, attr, *args, **kwargs)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/todd/base/_extensions/builtins.py", line 31, in getattr_recur
    return eval('obj' + attr)
  File "<string>", line 1, in <module>
NameError: name 'objstudent' is not defined

**Comment by LutingWang** [comment]
看起来是由于 todd 更新但是 HEAD 代码没有及时 push 导致的。我预计今天晚些时候 push 一下最新版代码

**Comment by Kingofolk** [comment]
收到！麻烦啦~~

**Comment by LutingWang** [comment]
hi同学，代码已经push了，还请再试一下。最近可能还会有一些更新，可以持续关注一下～

**Comment by Kingofolk** [comment]
您好，在代码成功train起来后，我在验证阶段又遇见了如下的错误：
2022-08-01T16:42:51+08:00" Traceback (most recent call last):
"2022-08-01T16:42:51+08:00"   File "tools/train.py", line 209, in <module>
"2022-08-01T16:42:51+08:00"     main()
"2022-08-01T16:42:51+08:00"   File "tools/train.py", line 196, in main
"2022-08-01T16:42:51+08:00"     train_detector(
"2022-08-01T16:42:51+08:00"   File "/data1/resources/code/HEAD-refactor/HEAD-refactor/head/train.py", line 236, in train_detector
"2022-08-01T16:42:51+08:00"     runner.run(data_loaders, cfg.workflow)
"2022-08-01T16:42:51+08:00"   File "/usr/local/miniconda3/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
"2022-08-01T16:42:51+08:00"     epoch_runner(data_loaders[i], **kwargs)
"2022-08-01T16:42:51+08:00"   File "/usr/local/miniconda3/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
"2022-08-01T16:42:51+08:00"     self.call_hook('after_train_epoch')
"2022-08-01T16:42:51+08:00"   File "/usr/local/miniconda3/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
"2022-08-01T16:42:51+08:00"     getattr(hook, fn_name)(self)
"2022-08-01T16:42:51+08:00"   File "/usr/local/miniconda3/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
"2022-08-01T16:42:51+08:00"     self._do_evaluate(runner)
"2022-08-01T16:42:51+08:00"   File "/data1/resources/code/mmdetection-master/mmdet/core/evaluation/eval_hooks.py", line 63, in _do_evaluate
"2022-08-01T16:42:51+08:00"     key_score = self.evaluate(runner, results)
"2022-08-01T16:42:51+08:00"   File "/usr/local/miniconda3/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 361, in evaluate
"2022-08-01T16:42:51+08:00"     eval_res = self.dataloader.dataset.evaluate(
"2022-08-01T16:42:51+08:00" TypeError: evaluate() got an unexpected keyword argument 'gpu_collect'

请问这个该怎么解决呢？麻烦您了！

**Comment by Kingofolk** [comment]
您好，在代码成功train起来后，我在验证阶段(验证快结束的时候)又遇见了如下的错误：
2022-08-01T16:42:51+08:00" Traceback (most recent call last):
"2022-08-01T16:42:51+08:00" File "tools/train.py", line 209, in
"2022-08-01T16:42:51+08:00" main()
"2022-08-01T16:42:51+08:00" File "tools/train.py", line 196, in main
"2022-08-01T16:42:51+08:00" train_detector(
"2022-08-01T16:42:51+08:00" File "/data1/resources/code/HEAD-refactor/HEAD-refactor/head/train.py", line 236, in train_detector
"2022-08-01T16:42:51+08:00" runner.run(data_loaders, cfg.workflow)
"2022-08-01T16:42:51+08:00" File "/usr/local/miniconda3/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
"2022-08-01T16:42:51+08:00" epoch_runner(data_loaders[i], **kwargs)
"2022-08-01T16:42:51+08:00" File "/usr/local/miniconda3/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
"2022-08-01T16:42:51+08:00" self.call_hook('after_train_epoch')
"2022-08-01T16:42:51+08:00" File "/usr/local/miniconda3/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
"2022-08-01T16:42:51+08:00" getattr(hook, fn_name)(self)
"2022-08-01T16:42:51+08:00" File "/usr/local/miniconda3/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
"2022-08-01T16:42:51+08:00" self._do_evaluate(runner)
"2022-08-01T16:42:51+08:00" File "/data1/resources/code/mmdetection-master/mmdet/core/evaluation/eval_hooks.py", line 63, in _do_evaluate
"2022-08-01T16:42:51+08:00" key_score = self.evaluate(runner, results)
"2022-08-01T16:42:51+08:00" File "/usr/local/miniconda3/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 361, in evaluate
"2022-08-01T16:42:51+08:00" eval_res = self.dataloader.dataset.evaluate(
"2022-08-01T16:42:51+08:00" TypeError: evaluate() got an unexpected keyword argument 'gpu_collect'

请问这个该怎么解决呢？麻烦您了！

**Comment by LutingWang** [comment]
刚刚提交的补丁修复了这个 bug，麻烦再试一下

**Comment by Kingofolk** [comment]
好嘞！谢谢~

**Comment by Kingofolk** [comment]
同学您好！我又来麻烦您了，请问您可以指导一下怎么进行分布式训练嘛。

**Comment by LutingWang** [comment]
客气了，可以参考下最新的readme
